[global]
dav-auth
dav-inf
shr: /s
allow-csrf
acao: https://share.ysood.xyz
shr-site: https://share.ysood.xyz/

hist: ~/.cache/copyparty

[accounts]
hbb: REPLACE_WITH_HBB_PASSWORD
obsidian: REPLACE_WITH_OBSIDIAN_PASSWORD
music: REPLACE_WITH_MUSIC_PASSWORD

# Virtual root - shows /downloads and /internal as subdirectories
[/]
    /data/data/com.termux/files/home/storage/internal/server/root_virtual/
    accs:
    rwdm: hbb

# Full access to the downloads folder
[/downloads]
    /data/data/com.termux/files/home/storage/internal/server/downloads/
    accs:
        rwdm: hbb

# Full access to internal folder
[/internal]
    /data/data/com.termux/files/home/storage/internal/
    accs:
        rwdm: hbb

[/sdcard]
    /data/data/com.termux/files/home/storage/sdcard/
    accs:
        rwdm: hbb

[/ariang]
    /data/data/com.termux/files/home/storage/internal/server/configs/aria2/ariang/
    accs:
    rwdm: hbb

[/upload]
    /data/data/com.termux/files/home/storage/internal/server/gphotosupload/
    accs:

[/obsidian]
    /data/data/com.termux/files/home/storage/internal/server/obsidian
    accs:
        rwmd.: obsidian
    flags:
        daw

[/incl]
    /data/data/com.termux/files/home/storage/internal/server/.aria2_incomplete
    accs:
    rwdm: hbb

[/music]
    /data/data/com.termux/files/home/storage/sdcard/Music/
    accs:
        rwdm: music
    flags:
        e2dsa
        e2ts
        fat32
        og
        og-ua: Discordbot|TelegramBot|Twitterbot|Slackbot|WhatsApp|facebookexternalhit
        og-title-a: {{ artist }} - {{ title }}

[/movies]
    /data/data/com.termux/files/home/storage/internal/server/movie-linked
    accs:
        rwdm: hbb
    flags:
        e2dsa
